words = [
    "augroup",
    "autocmd",
    "autocommands",
    "autoread",
    "axios",
    "bbuild",
    "bigfile",
    "cmdline",
    "codeium",
    "commitlint",
    "completeopt",
    "dcmake",
    "devicons",
    "djlint",
    "dmmulroy",
    "ecolog",
    "editmsg",
    "editorconfig",
    "equation",
    "fzf",
    "gitcommit",
    "grug",
    "htmldjango",
    "imaps",
    "keymap",
    "keymappings",
    "keymaps",
    "languagetool",
    "latexmk",
    "lazypath",
    "localleader",
    "lspconfig",
    "lspsaga",
    "menuone",
    "neovim",
    "noice",
    "noinsert",
    "noremap",
    "nowait",
    "nvim",
    "nvimdev",
    "oldfiles",
    "orgmode",
    "oxlint",
    "pinia",
    "proselint",
    "quickfile",
    "stdpath",
    "texlab",
    "textwidth",
    "trivy",
    "ttl",
    "underfull",
    "ver",
    "vimtex",
    "vlty",
    "vtsls",
    "zathura",
]
